The regression modeling it's one of the most common methods of Machine Learning

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LinearRegression

Let's load diabetes dataset

In [2]:
dataset = datasets.load_diabetes()

Checking data

In [3]:
dataset.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ..., 
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [4]:
dataset.target

array([ 151.,   75.,  141.,  206.,  135.,   97.,  138.,   63.,  110.,
        310.,  101.,   69.,  179.,  185.,  118.,  171.,  166.,  144.,
         97.,  168.,   68.,   49.,   68.,  245.,  184.,  202.,  137.,
         85.,  131.,  283.,  129.,   59.,  341.,   87.,   65.,  102.,
        265.,  276.,  252.,   90.,  100.,   55.,   61.,   92.,  259.,
         53.,  190.,  142.,   75.,  142.,  155.,  225.,   59.,  104.,
        182.,  128.,   52.,   37.,  170.,  170.,   61.,  144.,   52.,
        128.,   71.,  163.,  150.,   97.,  160.,  178.,   48.,  270.,
        202.,  111.,   85.,   42.,  170.,  200.,  252.,  113.,  143.,
         51.,   52.,  210.,   65.,  141.,   55.,  134.,   42.,  111.,
         98.,  164.,   48.,   96.,   90.,  162.,  150.,  279.,   92.,
         83.,  128.,  102.,  302.,  198.,   95.,   53.,  134.,  144.,
        232.,   81.,  104.,   59.,  246.,  297.,  258.,  229.,  275.,
        281.,  179.,  200.,  200.,  173.,  180.,   84.,  121.,  161.,
         99.,  109.,

For now, we'll create a object that have some properties of linear regression.

In [5]:
model = LinearRegression()

Fitting of the model using default properties

In [7]:
model.fit(dataset.data, dataset.target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

The expected object we'll recieve the data from target dataset.

In [10]:
expected = dataset.target

The object predicted we'll recieve the results of linear regression algorithm. 

In [13]:
predicted = model.predict(dataset.data)

With the model ajusted, we'll check the Mean Squared Error

In [14]:
mse = np.mean((predicted-expected)**2)

In [15]:
print ('Mean Squared Error:',mse)

Mean Squared Error: 2859.69039877


Mean Absolute Deviation metric

In [16]:
mad = np.mean (np.abs(expected - predicted))

In [17]:
print('Mean Absolute Deviation:',mad)

Mean Absolute Deviation: 43.2773950837


Determination Coefficient

In [18]:
print('R^2:', model.score(dataset.data, dataset.target))

R^2: 0.517749425413


Values of the coeficients

In [19]:
print('Values of Coeficients:', model.coef_)

Values of Coeficients: [ -10.01219782 -239.81908937  519.83978679  324.39042769 -792.18416163
  476.74583782  101.04457032  177.06417623  751.27932109   67.62538639]


Quantity of coefficients

In [20]:
print('Quantity of Coefficients:', len(model.coef_))

Quantity of Coefficients: 10


Intercept value

In [21]:
print('Value of intercept:', model.intercept_)

Value of intercept: 152.133484163


Model Results

In [22]:
predicted

array([ 206.11706979,   68.07234761,  176.88406035,  166.91796559,
        128.45984241,  106.34908972,   73.89417947,  118.85378669,
        158.81033076,  213.58408893,   97.07853583,   95.1016223 ,
        115.06673301,  164.67605023,  103.07517946,  177.17236996,
        211.75953205,  182.84424343,  147.99987605,  124.01702527,
        120.33094632,   85.80377894,  113.11286302,  252.44934852,
        165.48821056,  147.72187623,   97.12824075,  179.09342974,
        129.05497324,  184.78138552,  158.71515746,   69.47588393,
        261.50255826,  112.81897436,   78.37194762,   87.66624129,
        207.92460213,  157.87686037,  240.84370686,  136.93372685,
        153.48187659,   74.15703284,  145.63105805,   77.8280105 ,
        221.0786645 ,  125.22224022,  142.60147066,  109.4926324 ,
         73.14037106,  189.87368742,  157.93636782,  169.55816531,
        134.18186217,  157.72356219,  139.1077439 ,   72.73252701,
        207.8289973 ,   80.10834588,  104.08562488,  134.57807